ner_model_nameEntityRecognition_generateNameEntityRecognition:
    path:     /ner/{field}/{lang}
    defaults: { _controller: NERModelBundle:NameEntityRecognition:generateNameEntityRecognition }
    requirements:
        field:  \S{0,255}
        lang:  \S{0,255}