<?php

namespace RS\ModelBundle\Repository;

/**
 * RecommenderSearchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecommenderSearchRepository extends \Doctrine\ORM\EntityRepository
{
}
