<?php

namespace RS\ModelBundle\Repository;

/**
 * RecommenderResultsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecommenderResultsRepository extends \Doctrine\ORM\EntityRepository
{
}
