<?php

namespace RS\ModelBundle\Repository;

/**
 * RecommenderParametersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecommenderParametersRepository extends \Doctrine\ORM\EntityRepository
{
}
