<?php

namespace NER\ModelBundle\Repository;

/**
 * EuropeanaItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EuropeanaItemRepository extends \Doctrine\ORM\EntityRepository
{
}
