<?php

namespace NER\ModelBundle\Repository;

/**
 * NameEntityRecognitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NameEntityRecognitionRepository extends \Doctrine\ORM\EntityRepository
{
}
