<?php

namespace NER\ModelBundle\Repository;

/**
 * UploadFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadFileRepository extends \Doctrine\ORM\EntityRepository
{
}
