<?php

namespace DSG\ModelBundle\Repository;

/**
 * EuropeanaItemsSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EuropeanaItemsSessionRepository extends \Doctrine\ORM\EntityRepository
{
}
