dsg_home_home_index:
    path:     /
    defaults: { _controller: DSGHomeBundle:Home:index }

dsg_home_home_wait:
    path:     /wait/{europeanaItemsSession_id}
    defaults: { _controller: DSGHomeBundle:Home:wait }
    requirements:
        europeanaItemsSession_id: \d+

dsg_home_home_compute:
    path:     /compute/{europeanaItemsSession_id}
    defaults: { _controller: DSGHomeBundle:Home:compute }
    options:
        expose: true

dsg_home_home_result:
    path:     /result/{europeanaItemsSession_id}
    defaults: { _controller: DSGHomeBundle:Home:result }
    requirements:
        europeanaItemsSession_id: \d+

dsg_home_test_test:
    path:     /test
    defaults: { _controller: DSGHomeBundle:Test:test }