rs_home_home_index:
    path:     /
    defaults: { _controller: RSHomeBundle:Home:index }

rs_home_home_recommender:
    path:     /recommender/{recommenderSearch_id}
    defaults: { _controller: RSHomeBundle:Home:recommender }
    requirements:
        recommenderSearch_id: \d+

rs_home_dataset_index:
    path:     /dataset/
    defaults: { _controller: RSHomeBundle:DataSet:index }

rs_home_dataset_recommender:
    path:     /dataset/recommender/{recommenderParameter_id}
    defaults: { _controller: RSHomeBundle:DataSet:recommender }
    requirements:
        recommenderParameter_id: \d+